config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'dashboard#index'

  devise_for :users, :controllers => {
    :sessions => 'auth/sessions',
    :registrations => 'auth/registrations'
  }

  get 'dashboard', to: 'dashboard#index'

  # マスタ
  namespace :master do
    # オーナー
    get 'owners', to: 'owners#index'
    get 'owners/new', to: 'owners#new'
    post 'owners/create', to: 'owners#create'
    get 'owners/edit/(:id)', to: 'owners#edit', as: :owners_edit
    post 'owners/update', to: 'owners#update'

    # 施設
    get 'buildings', to: 'buildings#index'
    get 'buildings/new', to: 'buildings#new'
    post 'buildings/create', to: 'buildings#create'
    get 'buildings/show/(:id)', to: 'buildings#show', as: :buildings_show
    get 'buildings/edit/(:id)', to: 'buildings#edit', as: :buildings_edit
    post 'buildings/update', to: 'buildings#update'
    get 'buildings/invisible/(:id)', to: 'buildings#invisible', as: :buildings_invisible
    get 'buildings/visible/(:id)', to: 'buildings#visible', as: :buildings_visible
    get 'buildings/new_room/(:building_id)', to: 'buildings#new_room', as: :buildings_new_room
    post 'buildings/create_room', to: 'buildings#create_room'
    get 'buildings/edit_room/(:room_id)', to: 'buildings#edit_room', as: :buildings_edit_room
    post 'buildings/update_room', to: 'buildings#update_room'
    get 'buildings/(:building_id)/invisible_room/(:room_id)', to: 'buildings#invisible_room', as: :buildings_invisible_room
    get 'buildings/(:building_id)/visible_room/(:room_id)', to: 'buildings#visible_room', as: :buildings_visible_room

    # エリア
    get 'areas', to: 'areas#index'
    get 'areas/new', to: 'areas#new'
    post 'areas/create', to: 'areas#create'
    get 'areas/edit/(:id)', to: 'areas#edit', as: :areas_edit
    post 'areas/update', to: 'areas#update'

    # 精算書設定
    get 'settlement_template', to: 'settlement_template#index'
    post 'settlement_template/update', to: 'settlement_template#update'

    # アカウント
    get 'users', to: 'users#index'
    get 'users/new', to: 'users#new'
    get 'users/(:id)/edit', to: 'users#edit', as: :users_edit
    post 'users/create', to: 'users#create'
    post 'users/update', to: 'users#update'
    # post 'users/update', to: 'users#update'
    get 'users/(:id)/delete', to: 'users#delete', as: :users_delete
    get 'users/(:id)/restore', to: 'users#restore', as: :users_restore

  end

  # モーダル
  namespace :modal do
    post 'search_reservation/previous_reservation', to: 'search_reservation#previous_reservation'
    post 'search_reservation/whole_reservation_status', to: 'search_reservation#whole_reservation_status'
  end

  # 予約管理
  # 各種一覧加減を起点としてアクセスされる（パンくずリストで一覧に戻る）可能性のあるアクションは全て/(:callback)をもたせる
  namespace :reservation_management do
    get 'entry/', to: 'entry#new'
    get 'entry/(:check_in_date)/(:room_id)/(:callback)', to: 'entry#new', as: :entry_date
    get 'show/(:id)/(:callback)', to: 'entry#show', as: :show
    get 'edit/(:id)/(:callback)', to: 'entry#edit', as: :edit
    post 'entry/create/(:callback)', to: 'entry#create', as: :create
    post 'entry/update/(:callback)', to: 'entry#update', as: :update
    get 'edit_reservation_date/(:reservation_id)', to: 'entry#edit_reservation_date', as: :edit_reservation_date
    post 'update_reservation_date', to: 'entry#update_reservation_date'
    post 'entry/bulk_forward_status/(:callback)', to: 'entry#bulk_forward_status', as: :bulk_forward_status
    post 'entry/forward_status/(:callback)', to: 'entry#forward_status', as: :forward_status
    post 'entry/cancel/(:callback)', to: 'entry#cancel', as: :cancel

    # 一棟貸
    get 'whole_reservation/new/(:check_in_date)/(:building_id)/(:callback)', to: 'whole_reservation#new', as: :whole_reservation_new
    get 'whole_reservation/show/(:id)/(:reservation_id)/(:callback)', to: 'whole_reservation#show', as: 'whole_reservation_show'
    post 'whole_reservation/create/(:callback)', to: 'whole_reservation#create', as: :whole_reservation_create
    get 'whole_reservation/edit_basic/(:id)', to: 'whole_reservation#edit_basic', as: :whole_reservation_edit_basic
    post 'whole_reservation/update_basic', to: 'whole_reservation#update_basic', as: :whole_reservation_update_basic
    get 'whole_reservation/edit_payment/(:id)', to: 'whole_reservation#edit_payment', as: :whole_reservation_edit_payment
    post 'whole_reservation/update_payment', to: 'whole_reservation#update_payment', as: :whole_reservation_update_payment
    get 'whole_reservation/edit_room_reservations/(:id)', to: 'whole_reservation#edit_room_reservations', as: :whole_reservation_edit_room_reservations
    post 'whole_reservation/update_room_reservations', to: 'whole_reservation#update_room_reservations', as: :whole_reservation_update_room_reservations
    post 'whole_reservation/cancel/(:callback)', to: 'whole_reservation#cancel', as: :whole_reservation_cancel

    # インポート
    get 'import/', to: 'import#index'
    post 'import/comfirm', to: 'import#comfirm'
    post 'import/create', to: 'import#create'
    get 'import/result', to: 'import#result'

    # 施設別月間予約一覧
    get 'monthly_list', to: 'monthly_list#index'
    post 'monthly_list/search', to: 'monthly_list#search'
    get 'monthly_list/transition_search', to: 'monthly_list#transition_search'
    get 'monthly_list/csv', to: 'monthly_list#csv'

    # 日別予約一覧
    get 'daily_list', to: 'daily_list#index'
    post 'daily_list/search', to: 'daily_list#search'
    get 'daily_list/transition_search', to: 'daily_list#transition_search'

    # インポート
    get 'import_suitebook/', to: 'import_suitebook#index'
    post 'import_suitebook/create', to: 'import_suitebook#create'

    # 予約検索
    get 'reservations', to: 'reservations#index'
    post 'reservations/search', to: 'reservations#search'
    get 'reservations/transition_search', to: 'reservations#transition_search'

    # suitebook連携
    get 'suitebook', to: 'suitebook#index'
    post 'suitebook/search', to: 'suitebook#search'
    get 'suitebook/transition_search', to: 'suitebook#transition_search'
    get 'suitebook/:id/cancel', to: 'suitebook#cancel', as: :suitebook_cancel
    get 'suitebook/:id/show/(:callback)', to: 'suitebook#show', as: :suitebook_show
    get 'suitebook/:id/entry/(:callback)', to: 'suitebook#entry', as: :suitebook_entry
    get 'suitebook/:id/entry_whole_select_building/(:callback)', to: 'suitebook#entry_whole_select_building', as: :suitebook_entry_whole_select_building
    post 'suitebook/:id/entry_whole/(:callback)', to: 'suitebook#entry_whole', as: :suitebook_entry_whole
    post 'suitebook/create/(:callback)', to: 'suitebook#create', as: :suitebook_create
    post 'suitebook/create_whole/(:callback)', to: 'suitebook#create_whole', as: :suitebook_create_whole
  end

  # 作業管理
  namespace :work do
    get 'daily_tasks', to: 'daily_tasks#index'
    post 'daily_tasks/search', to: 'daily_tasks#search'
    get 'daily_tasks/transition_search', to: 'daily_tasks#transition_search'
    get 'daily_tasks/forward_status/(:id)/(:status)', to: 'daily_tasks#forward_status', as: :daily_tasks_forward_status

    get 'cleaning_status_list', to: 'cleaning_status_list#index'
    post 'cleaning_status_list/search', to: 'cleaning_status_list#search'
    get 'cleaning_status_list/transition_search', to: 'cleaning_status_list#transition_search'
    get 'cleaning_status_list/forward_status/(:id)/(:status)', to: 'cleaning_status_list#forward_status', as: :cleaning_status_list_forward_status
  end

  # 月事管理
  namespace :summary do
    # 売上一覧
    get 'sales_list', to: 'sales_list#index'
    post 'sales_list/search', to: 'sales_list#search'
    get 'sales_list/transition_search', to: 'sales_list#transition_search'
    get 'sales_list/csv', to: 'sales_list#csv'

    # 精算書
    get  'settlement/(:room_id)/(:year_month)/new', to: 'settlement#new', as: :settlement
    post 'settlement/create', to: 'settlement#create', as: :settlement_create
    get  'settlement/(:id)/edit', to: 'settlement#edit', as: :settlement_edit
    get  'settlement/(:id)/delete', to: 'settlement#delete', as: :settlement_delete
    patch 'settlement/update', to: 'settlement#update', as: :settlement_update
    get  'settlement/(:id)/refresh_reward_rate', to: 'settlement#refresh_reward_rate', as: :settlement_refresh_reward_rate
    get  'settlement/(:id)/print', to: 'settlement#print', as: :settlement_print
    get  'settlement/(:id)/excel', to: 'settlement#excel', as: :settlement_excel
    get  'settlement/(:id)/xlsx', to: 'settlement#xlsx', as: :settlement_xlsx

    # 月次レポート
    get 'reports', to: 'reports#index'
    post 'reports/accommodation_tax', to: 'reports#accommodation_tax'
    post 'reports/accommodation_tax_for_room', to: 'reports#accommodation_tax_for_room'
    post 'reports/accommodation_tax_for_building', to: 'reports#accommodation_tax_for_building'
    post 'reports/accommodation_tax_for_daily_room', to: 'reports#accommodation_tax_for_daily_room'
  end

  # 共通
  # Ajax用
  get 'select_room_options_by_area/(:area_id)', to: 'ajax#select_room_options_by_area', as: :select_room_options_by_area

  # その他
  namespace :other do
    get 'release_notes', to: 'release_notes#index'
  end

  # ルーティングエラーは（これより上で指定したルーティングに引っかからない）全てのURLをキャッチして処理
  match "*path" => "application#handle_404", via: :all unless Rails.env.development?
end

app/controllers/summary/reports_controller.rb
class Summary::ReportsController < ApplicationController
  def index
    @form = Summary::Reports::IndexForm.new
  end

  def accommodation_tax
    search_month = params.dig(:accommodation_tax_csv, :search_month)
    @form = Summary::Reports::AccommodationTaxCsvForm.new(search_month: search_month, action_name: action_name)
    send_data render_to_string, filename: @form.file_name, type: 'text/csv; charset=shift_jis'
  end

  def accommodation_tax_for_room
    search_month = params.dig(:accommodation_tax_csv_for_room, :search_month)
    @form = Summary::Reports::AccommodationTaxCsvForm.new(search_month: search_month, action_name: action_name)
    send_data render_to_string, filename: @form.file_name, type: 'text/csv; charset=shift_jis'
  end

  def accommodation_tax_for_building
    search_month = params.dig(:accommodation_tax_csv_for_building, :search_month)
    @form = Summary::Reports::AccommodationTaxCsvForm.new(search_month: search_month, action_name: action_name)
    send_data render_to_string, filename: @form.file_name, type: 'text/csv; charset=shift_jis'
  end

  # def accommodation_tax_for_date_room
  #   search_month = params.dig(:accommodation_tax_csv_for_building, :search_month)
  #   @form = Summary::Reports::AccommodationTaxCsvForm.new(search_month: search_month, action_name: action_name)
  # end

  def csv
    @form = Summary::SalesListForm.new(fetch_search_conditions)
    if @form.valid?
      @form.fetch_list(is_csv: true)
    end
    send_data render_to_string, filename: @form.csv_file_name, type: 'text/csv; charset=shift_jis'
  end
end

app/controllers/summary/sales_list_controller.rb
class Summary::SalesListController < ApplicationController
  # コールバック変数のセット
  before_action -> {
    set_callback(:sales_list)
  }

  def index
    clear_search_conditions
    @form = Summary::SalesListForm.new(is_show_all_rooms: params.dig(:show_all_rooms).to_bool) # params は show_all_rooms の有無のみ
    # @form.show_all_rooms = true if params.dig(:show_all_rooms).to_bool
    @form.fetch_list
    @settlement_by_room_id = @form.get_settlement_by_room
  end

  def search
    @form = Summary::SalesListForm.new(search_params)
    if @form.valid?
      @form.fetch_list
      @settlement_by_room_id = @form.get_settlement_by_room
      set_search_conditions
    end
  rescue => ex
    render "shared/ajax_error"
  end

  # 検索条件をセッションから取得して一覧表示
  def transition_search
    @form = Summary::SalesListForm.new(fetch_search_conditions)
    @form.fetch_list
    @settlement_by_room_id = @form.get_settlement_by_room
    render :index
  end

  def csv
    # 直前の検索したIDを保持しているので、is_show_all_rooms は常にtrueでわたす >>> 2020-10-25 CSV出力時は問答無用でfalseを渡すように変更
    @form = Summary::SalesListForm.new(fetch_search_conditions, is_show_all_rooms: false)
    if @form.valid?
      @form.fetch_list(is_csv: true)
    end
    send_data render_to_string, filename: @form.csv_file_name, type: 'text/csv; charset=shift_jis'
  end

  private

  def search_params
    params.require(:summary_sales_list_form).permit(
      :search_check_in_month, :search_original_month, :search_prev_next_month,
      :show_all_rooms,
      search_room_ids: []
    )
  end
end

app/helpers/summary/settlement_helper.rb
module Summary::SettlementHelper
  # 年月表示プレースホルダー置換
  def convert_year_month_format_title(format, year_month, is_next = false)
    fromat_str = format.gsub('${Y}', '%Y')
    fromat_str = fromat_str.gsub('${M}', '%m')
    fromat_str = fromat_str.gsub('${m}', '%-m')

    # 年月6桁に01日を足して日付にしてフォーマット
    if is_next
      "#{year_month}01".to_date.next_month.strftime(fromat_str)
    else
      "#{year_month}01".to_date.strftime(fromat_str)
    end
  end

  # エクセル用シート名
  def sheet_name(year_month, building_name)

    # 年月6桁に01日を足して日付にしてフォーマット
    "#{year_month}01".to_date.strftime("%Y年%m月_#{building_name}")

  end

end

app/views/summary/sales_list/_button_list.html.slim
.row style="margin-top: 10px;"
  / ▼ 左寄せ

  .col-sm-6
    - if form.room_id_hash.size > 0
      = form_tag(summary_sales_list_csv_path(format: :csv), method: :get, id: :csv_download_form)
        button.btn.btn-default.csv_download type="button" CSVダウンロード

  / ▼ 右寄せ
  .col-sm-6.text-right
    / ボタン押下時のJSの処理は _list.html.slimに記述
    button.btn.btn-default.prev_month type="submit" style="margin-left: 2px;"
      i.fa.fa-fw.fa-arrow-left
      | 前月を検索
    button.btn.btn-default.next_month type="submit" style="margin-left: 2px;"
      | 次月を検索
      i.fa.fa-fw.fa-arrow-right

app/views/summary/sales_list/_list.html.slim
.row
  .col-sm-12
    .box.box-warning
      .box-header
        h3.box-title
          = "#{form.search_check_in_month}【日数: #{form.day_count}日】"
          span.monthly_total
            | 売上合計:
            i.fa.fa-fw.fa-yen
            = form.monthly_total[:total].to_s :delimited

          span.monthly_total
            |（宿泊費:
            i.fa.fa-fw.fa-yen
            = form.monthly_total[:total_room_charge].to_s :delimited

          span.monthly_total
            |&nbsp;清掃費:
            i.fa.fa-fw.fa-yen
            = form.monthly_total[:total_cleaning_fee].to_s :delimited

          span.monthly_total
            |&nbsp;食事代:
            i.fa.fa-fw.fa-yen
            = form.monthly_total[:total_meal_fee].to_s :delimited
            |）
            / = "（宿泊費： 清掃費： 食事代：）"

        = render 'button_list', form: form

      .box-body.table_wrapper
        table.table.table-bordered#table_sales_list
          thead
            tr.small
              th.code
              th.building 施設名 - 部屋名
              th 件数
              th 売上
              th 宿泊費
              th 清掃費
              th 食事代
              th 稼働日
              th OCC
              th ゲスト数
              th DOR
              th ADR
              th 人数<br>単価
              th RevPAR
              th 精算書
          tbody.disp-vline
            - form.search_room_ids.each do |id|
              - room = form.rooms[id]
              - next if room.nil?
              - values = form.room_id_hash[id]
              - values ||= {}
              tr class= cycle('odd', 'even')
                td.code = room.building_code
                td.building = [room.building_name, room.name.presence].compact.join(' - ')
                td.reservation_count = values[:reservation_count]
                td.sum_total        = values[:sum_total]
                td.sum_room_charge  = values[:sum_room_charge]
                td.sum_cleaning_fee = values[:sum_cleaning_fee]
                td.sum_meal_fee     = values[:sum_meal_fee]
                td.opration_count = values[:operation_count]
                td.occ            = values[:occ]
                td.sum_guest      = values[:sum_guest]
                td.dor            = values[:dor]
                td.adr            = values[:adr]
                td.unit_price     = values[:unit_price]
                td.rev_par        = values[:rev_par]
                td.settlement
                  / - if values[:sum_total].to_i > 0
                  - settlement = settlement_by_room_id[room.id]
                  - if settlement
                    small = link_to '作成済', summary_settlement_edit_path(settlement.id)
                    |&nbsp;
                    i.fa.fa-fw.fa-clock-o data-toggle="tooltip" data-placement="top" title="#{settlement.created_at.to_s(:datetime)}"
                  - else
                    small= link_btn_tag('作成する', summary_settlement_path(id, form.year_month), button_class: 'btn-success btn-xs')

      .box-footer
        = render 'button_list', form: form
        h4
          = "#{form.search_check_in_month}【日数: #{form.day_count}日】"
          span.monthly_total
            | 売上合計：
            i.fa.fa-fw.fa-yen
            = form.monthly_total[:total].to_s :delimited

= render 'list_js', form: form

app/views/summary/sales_list/_list_js.html.erb
<script>
  $(function () {
    $('#table_sales_list').DataTable({
      <%= data_table_options not_sort: [], searching: true, lengthMenu: '[100]', lengthChange: false %>
    });
  });

  // rails-ujs を利用している場合、JSからsubmit()を呼ぶとremote: trueにならない（Ajaxにならない）
  // https://blog.rista.jp/entry/2017/09/04/100006
  $('.prev_month').click(function() {
    var month = '<%= l(form.search_original_month - 1.month, format: :default_h) %>';
    $('#summary_sales_list_form_search_prev_next_month').val(month);
    Rails.fire($('#sales_list_form')[0], 'submit');
  });

  $('.next_month').click(function() {
    var month = '<%= l(form.search_original_month + 1.month, format: :default_h) %>';
    $('#summary_sales_list_form_search_prev_next_month').val(month);
    Rails.fire($('#sales_list_form')[0], 'submit');
  });

  $('.csv_download').click(function() {
    var form = $('#csv_download_form');
    form.submit();
    // Rails.fire(form, 'submit');
    stopSpin(form);
  });
</script>

app/views/summary/sales_list/_search.html.slim
sass:
  .select2-container--default .select2-selection--multiple .select2-selection__choice
    color: black

  .select2-container--default
    width: 100%
    border-radius: 0

  .content-wrapper
    min-height: 200px

= form_for form, url: {action: :search}, html: {class: 'form-horizontal', id: 'sales_list_form'}, remote: true do |f|
  = f.hidden_field :show_all_rooms

  .box
    .box-header.with-border
      .box-title
        |検索条件

        - if form.show_all_rooms
          span.show_all_rooms_link.attention ※施設の選択肢に非表示の部屋が含まれています。
        - else
          = link_to summary_sales_list_path(show_all_rooms: true), class: "show_all_rooms_link" do
            i.fa.fa-search
            |非表示の部屋も含めて検索

      .box-tools.pull-right
        button.btn.btn-box-tool type="button" data-widget="collapse" data-toggle="tooltip" title="" data-original-title="Collapse"
          |検索条件ウィンドウを開閉する&nbsp;
          i.fa.fa-minus

    .box-body
      / エラーメッセージの表示
      / .col-sm-12#search_error_messages

      //
      // NOTE: 検索条件を増やす場合、CSV出力の検索条件用に '_button_list.html.slim'
      // にもhiddenタグを追加すること
      //
      .form-group
        label.col-sm-2.control-label for="search_check_in_month"
          |対象月
          span.require ＊

        .col-sm-2
          .input-group
            = f.text_field :search_check_in_month, class: "form-control year_month"
            = f.hidden_field :search_prev_next_month
            span.input-group-addon
              i.fa.fa-calendar

      - unless form.show_all_rooms
        .form-group
          label.col-sm-2.control-label
            |エリア
            i.fa.fa-fw.fa-question-circle data-toggle="tooltip" data-placement="top" title="施設の自動選択を行います。選択したエリア自体は検索条件に含まれません。"
          .col-sm-3
            - area_select_options = Area.visible.map { |a| [ a.name, a.id, data: { children_path: select_room_options_by_area_path(a) } ] }
            - area_select_options = [['全て', 0, data: { children_path: select_room_options_by_area_path(0) }]] + area_select_options
            = f.select :search_area_id, area_select_options, {include_blank: false}, class: "form-control select-parent select2", style: "font-size: 10px;"

      .form-group
        label.col-sm-2.control-label for="search_room_id"
          |施設
          span.require ＊
        .col-sm-10
          = f.select :search_room_ids, options_for_select( room_select_options(form.show_all_rooms), form.search_room_ids ), {}, {class: "form-control select2-multi select-children", multiple: "multiple", tabindex: 1}

    .box-footer style=("display: block;")
      | 検索条件を指定してください。
      .pull-right
        button.btn.btn-default type="submit" style="margin-left: 20px;" tabindex="3"
          i.fa.fa-search
          | 検索


/ 連動セレクト（団地選択時に部屋情報のセレクトオプションタグを自動生成）
= render 'shared/replace_select_option_js'

app/views/summary/sales_list/index.html.slim
- breadcrumb :sales_list
- provide(:title, t("title.summary.sales_list"))

.row
  .col-xs-12
    .box.box-primary
      .box-tools.pull-right
        button.btn.btn-box-tool type="button" data-widget="remove"
          i.fa.fa-remove
      .box-body
        p 部屋別で全部屋の月間売上を一覧で確認できます。
        ul
          li 一覧のヘッダー横のアイコンをクリックするとその項目でデータをソートします。
          li 一覧右上の検索窓は、現在表示されている一覧に対して絞り込みができます。
          li 「CSVダウンロード」ボタンで直前の検索結果をCSVファイルでダウンロードできます。

#message
  = render 'shared/error_messages', obj: @form

/ 検索条件
#search
  = render 'search', form: @form

#sales_list
  = render 'list', form: @form, settlement_by_room_id: @settlement_by_room_id

app/views/summary/sales_list/search.js.erb
<% if @form.errors.empty? %>
  $('#search_error_messages').html('');
  $('#sales_list').html('<%= j(render "list", form: @form, settlement_by_room_id: @settlement_by_room_id) %>');

  // 検索条件対象月の値のみ更新
  $('#summary_sales_list_form_search_check_in_month').val('<%= @form.search_check_in_month %>')

<% else %>
  $('#search_error_messages').html('<%= j(render "shared/error_messages", obj: @form) %>');
<% end %>

// Ajaxでのパーシャル更新時は明示的ローディングを停止させる
stopSpin($('#sales_list_form'));