config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'dashboard#index'

  devise_for :users, :controllers => {
    :sessions => 'auth/sessions',
    :registrations => 'auth/registrations'
  }

  get 'dashboard', to: 'dashboard#index'

  # マスタ
  namespace :master do
    # オーナー
    get 'owners', to: 'owners#index'
    get 'owners/new', to: 'owners#new'
    post 'owners/create', to: 'owners#create'
    get 'owners/edit/(:id)', to: 'owners#edit', as: :owners_edit
    post 'owners/update', to: 'owners#update'

    # 施設
    get 'buildings', to: 'buildings#index'
    get 'buildings/new', to: 'buildings#new'
    post 'buildings/create', to: 'buildings#create'
    get 'buildings/show/(:id)', to: 'buildings#show', as: :buildings_show
    get 'buildings/edit/(:id)', to: 'buildings#edit', as: :buildings_edit
    post 'buildings/update', to: 'buildings#update'
    get 'buildings/invisible/(:id)', to: 'buildings#invisible', as: :buildings_invisible
    get 'buildings/visible/(:id)', to: 'buildings#visible', as: :buildings_visible
    get 'buildings/new_room/(:building_id)', to: 'buildings#new_room', as: :buildings_new_room
    post 'buildings/create_room', to: 'buildings#create_room'
    get 'buildings/edit_room/(:room_id)', to: 'buildings#edit_room', as: :buildings_edit_room
    post 'buildings/update_room', to: 'buildings#update_room'
    get 'buildings/(:building_id)/invisible_room/(:room_id)', to: 'buildings#invisible_room', as: :buildings_invisible_room
    get 'buildings/(:building_id)/visible_room/(:room_id)', to: 'buildings#visible_room', as: :buildings_visible_room

    # エリア
    get 'areas', to: 'areas#index'
    get 'areas/new', to: 'areas#new'
    post 'areas/create', to: 'areas#create'
    get 'areas/edit/(:id)', to: 'areas#edit', as: :areas_edit
    post 'areas/update', to: 'areas#update'

    # 精算書設定
    get 'settlement_template', to: 'settlement_template#index'
    post 'settlement_template/update', to: 'settlement_template#update'

    # アカウント
    get 'users', to: 'users#index'
    get 'users/new', to: 'users#new'
    get 'users/(:id)/edit', to: 'users#edit', as: :users_edit
    post 'users/create', to: 'users#create'
    post 'users/update', to: 'users#update'
    # post 'users/update', to: 'users#update'
    get 'users/(:id)/delete', to: 'users#delete', as: :users_delete
    get 'users/(:id)/restore', to: 'users#restore', as: :users_restore

  end

  # モーダル
  namespace :modal do
    post 'search_reservation/previous_reservation', to: 'search_reservation#previous_reservation'
    post 'search_reservation/whole_reservation_status', to: 'search_reservation#whole_reservation_status'
  end

  # 予約管理
  # 各種一覧加減を起点としてアクセスされる（パンくずリストで一覧に戻る）可能性のあるアクションは全て/(:callback)をもたせる
  namespace :reservation_management do
    get 'entry/', to: 'entry#new'
    get 'entry/(:check_in_date)/(:room_id)/(:callback)', to: 'entry#new', as: :entry_date
    get 'show/(:id)/(:callback)', to: 'entry#show', as: :show
    get 'edit/(:id)/(:callback)', to: 'entry#edit', as: :edit
    post 'entry/create/(:callback)', to: 'entry#create', as: :create
    post 'entry/update/(:callback)', to: 'entry#update', as: :update
    get 'edit_reservation_date/(:reservation_id)', to: 'entry#edit_reservation_date', as: :edit_reservation_date
    post 'update_reservation_date', to: 'entry#update_reservation_date'
    post 'entry/bulk_forward_status/(:callback)', to: 'entry#bulk_forward_status', as: :bulk_forward_status
    post 'entry/forward_status/(:callback)', to: 'entry#forward_status', as: :forward_status
    post 'entry/cancel/(:callback)', to: 'entry#cancel', as: :cancel

    # 一棟貸
    get 'whole_reservation/new/(:check_in_date)/(:building_id)/(:callback)', to: 'whole_reservation#new', as: :whole_reservation_new
    get 'whole_reservation/show/(:id)/(:reservation_id)/(:callback)', to: 'whole_reservation#show', as: 'whole_reservation_show'
    post 'whole_reservation/create/(:callback)', to: 'whole_reservation#create', as: :whole_reservation_create
    get 'whole_reservation/edit_basic/(:id)', to: 'whole_reservation#edit_basic', as: :whole_reservation_edit_basic
    post 'whole_reservation/update_basic', to: 'whole_reservation#update_basic', as: :whole_reservation_update_basic
    get 'whole_reservation/edit_payment/(:id)', to: 'whole_reservation#edit_payment', as: :whole_reservation_edit_payment
    post 'whole_reservation/update_payment', to: 'whole_reservation#update_payment', as: :whole_reservation_update_payment
    get 'whole_reservation/edit_room_reservations/(:id)', to: 'whole_reservation#edit_room_reservations', as: :whole_reservation_edit_room_reservations
    post 'whole_reservation/update_room_reservations', to: 'whole_reservation#update_room_reservations', as: :whole_reservation_update_room_reservations
    post 'whole_reservation/cancel/(:callback)', to: 'whole_reservation#cancel', as: :whole_reservation_cancel

    # インポート
    get 'import/', to: 'import#index'
    post 'import/comfirm', to: 'import#comfirm'
    post 'import/create', to: 'import#create'
    get 'import/result', to: 'import#result'

    # 施設別月間予約一覧
    get 'monthly_list', to: 'monthly_list#index'
    post 'monthly_list/search', to: 'monthly_list#search'
    get 'monthly_list/transition_search', to: 'monthly_list#transition_search'
    get 'monthly_list/csv', to: 'monthly_list#csv'

    # 日別予約一覧
    get 'daily_list', to: 'daily_list#index'
    post 'daily_list/search', to: 'daily_list#search'
    get 'daily_list/transition_search', to: 'daily_list#transition_search'

    # インポート
    get 'import_suitebook/', to: 'import_suitebook#index'
    post 'import_suitebook/create', to: 'import_suitebook#create'

    # 予約検索
    get 'reservations', to: 'reservations#index'
    post 'reservations/search', to: 'reservations#search'
    get 'reservations/transition_search', to: 'reservations#transition_search'

    # suitebook連携
    get 'suitebook', to: 'suitebook#index'
    post 'suitebook/search', to: 'suitebook#search'
    get 'suitebook/transition_search', to: 'suitebook#transition_search'
    get 'suitebook/:id/cancel', to: 'suitebook#cancel', as: :suitebook_cancel
    get 'suitebook/:id/show/(:callback)', to: 'suitebook#show', as: :suitebook_show
    get 'suitebook/:id/entry/(:callback)', to: 'suitebook#entry', as: :suitebook_entry
    get 'suitebook/:id/entry_whole_select_building/(:callback)', to: 'suitebook#entry_whole_select_building', as: :suitebook_entry_whole_select_building
    post 'suitebook/:id/entry_whole/(:callback)', to: 'suitebook#entry_whole', as: :suitebook_entry_whole
    post 'suitebook/create/(:callback)', to: 'suitebook#create', as: :suitebook_create
    post 'suitebook/create_whole/(:callback)', to: 'suitebook#create_whole', as: :suitebook_create_whole
  end

  # 作業管理
  namespace :work do
    get 'daily_tasks', to: 'daily_tasks#index'
    post 'daily_tasks/search', to: 'daily_tasks#search'
    get 'daily_tasks/transition_search', to: 'daily_tasks#transition_search'
    get 'daily_tasks/forward_status/(:id)/(:status)', to: 'daily_tasks#forward_status', as: :daily_tasks_forward_status

    get 'cleaning_status_list', to: 'cleaning_status_list#index'
    post 'cleaning_status_list/search', to: 'cleaning_status_list#search'
    get 'cleaning_status_list/transition_search', to: 'cleaning_status_list#transition_search'
    get 'cleaning_status_list/forward_status/(:id)/(:status)', to: 'cleaning_status_list#forward_status', as: :cleaning_status_list_forward_status
  end

  # 月事管理
  namespace :summary do
    # 売上一覧
    get 'sales_list', to: 'sales_list#index'
    post 'sales_list/search', to: 'sales_list#search'
    get 'sales_list/transition_search', to: 'sales_list#transition_search'
    get 'sales_list/csv', to: 'sales_list#csv'

    # 精算書
    get  'settlement/(:room_id)/(:year_month)/new', to: 'settlement#new', as: :settlement
    post 'settlement/create', to: 'settlement#create', as: :settlement_create
    get  'settlement/(:id)/edit', to: 'settlement#edit', as: :settlement_edit
    get  'settlement/(:id)/delete', to: 'settlement#delete', as: :settlement_delete
    patch 'settlement/update', to: 'settlement#update', as: :settlement_update
    get  'settlement/(:id)/refresh_reward_rate', to: 'settlement#refresh_reward_rate', as: :settlement_refresh_reward_rate
    get  'settlement/(:id)/print', to: 'settlement#print', as: :settlement_print
    get  'settlement/(:id)/excel', to: 'settlement#excel', as: :settlement_excel
    get  'settlement/(:id)/xlsx', to: 'settlement#xlsx', as: :settlement_xlsx

    # 月次レポート
    get 'reports', to: 'reports#index'
    post 'reports/accommodation_tax', to: 'reports#accommodation_tax'
    post 'reports/accommodation_tax_for_room', to: 'reports#accommodation_tax_for_room'
    post 'reports/accommodation_tax_for_building', to: 'reports#accommodation_tax_for_building'
    post 'reports/accommodation_tax_for_daily_room', to: 'reports#accommodation_tax_for_daily_room'
  end

  # 共通
  # Ajax用
  get 'select_room_options_by_area/(:area_id)', to: 'ajax#select_room_options_by_area', as: :select_room_options_by_area

  # その他
  namespace :other do
    get 'release_notes', to: 'release_notes#index'
  end

  # ルーティングエラーは（これより上で指定したルーティングに引っかからない）全てのURLをキャッチして処理
  match "*path" => "application#handle_404", via: :all unless Rails.env.development?
end

app/controllers/reservation_management/daily_list_controller.rb
class ReservationManagement::DailyListController < ApplicationController

  # コールバック変数のセット
  before_action -> {
    set_callback(:daily_list)
  }, only: [:index, :search, :transition_search]

  # GET /reservation/daily_list
  #
  def index
    clear_search_conditions
    @form = ReservationManagement::DailyListForm.new
    # @form.reservation_list
  end

  # POST /reservation/daily_list/search
  #
  def search
    @form = ReservationManagement::DailyListForm.new(search_params)
    set_search_conditions
  end

  # GET /reservation/daily_list/transition_search
  #
  # 検索条件をセッションから取得して一覧表示
  def transition_search
    @form = ReservationManagement::DailyListForm.new(fetch_search_conditions)
    render :index
  end

  private

  def search_params
    params.require(:reservation_management_daily_list_form).permit(:search_check_in_day, :search_check_in_date_flag)
  end
end

app/controllers/reservation_management/entry_controller.rb
class ReservationManagement::EntryController < ApplicationController

  # コールバック変数の保持
  before_action :fetch_callback

  # GET /new
  #
  def new
    @form = ReservationManagement::Reservations::EntryForm.new(params: params)
  end

  def edit
    # TODO: キャンセル済のデータにアクセスしない実装にする
    @form = ReservationManagement::Reservations::EntryForm.new(reservation_id: params[:id])
  end

  def show
    @form = ReservationManagement::Reservations::ShowForm.new(id: params[:id])
  end

  def create
    @form = ReservationManagement::Reservations::EntryForm.new(params: create_params)
    if @form.valid?
      service = ReservationManagement::EntryService.new
      reservation = service.apply(@form.attributes)
      redirect_to reservation_management_show_path(reservation.id, @callback), flash: {success: "予約情報を登録しました。日別の請求金額は自動で配分されていますので確認してください。"}
    else
      render :new
    end
  end

  def update
    # TODO: キャンセル済のデータにアクセスしない実装にする
    @form = ReservationManagement::Reservations::EntryForm.new(params: update_params, reservation_id: update_params[:reservation_id])
    if @form.valid?
      service = ReservationManagement::EntryService.new

      # TODO: この辺処理をフォームに移譲したい
      attributes = @form.whole_reservation_id ? update_params_for_whole : update_params
      attributes = attributes.merge(
        id: @form.id,
        scheduled_check_in_time: @form.scheduled_check_in_time,
        set_nil: true)
      reservation = service.apply(attributes)
      redirect_to reservation_management_show_path(reservation.id, @callback), flash: {success: "予約情報を更新しました。"}
    else
      render :edit
    end
  end

  def edit_reservation_date
    @form = ReservationManagement::Reservations::EditReservationDateForm.new(params[:reservation_id])
  end

  def update_reservation_date
    @edit_form = ReservationManagement::Reservations::EditReservationDateForm.new(
              params[:reservation_management_reservations_edit_reservation_date_form][:reservation_id],
              update_reservation_date_params)
    if @edit_form.valid?
      # ActiveRecord::StaleObjectError

      # TODO: サービスにフォームオブジェクトをそのままわたしてる
      reservation = ReservationManagement::UpdateReservationDateService.update(@edit_form.reservation)
      flash.now[:success] = '請求内訳を更新しました。'
      # 参照画面のFormをつくりなおし
      @form = ReservationManagement::Reservations::ShowForm.new(id: reservation.id)
    end
  end

  def bulk_forward_status
    _p = forward_status_params
    ReservationManagement::UpdateStatusService.forward_status(reservation_id: _p[:id], current_status: _p[:status], is_bulk: true)
    flash[:success] = 'ステータスを更新しました。'
  rescue Service::UpdateFailure => ex
    flash[:error] = ex.message
  ensure
    redirect_to reservation_management_show_path(_p[:id], @callback)
  end

  def forward_status
    _p = forward_status_params
    ReservationManagement::UpdateStatusService.forward_status(reservation_id: _p[:id], current_status: _p[:status])
    flash[:success] = 'ステータスを更新しました。'
  rescue Service::UpdateFailure => ex
    flash[:error] = ex.message
  ensure
    redirect_to reservation_management_show_path(_p[:id], @callback)
  end

  def cancel
    _p = forward_status_params
    ReservationManagement::UpdateStatusService.cancel_status(current_status: _p[:status], reservation_id: _p[:id])
    flash[:success] = '予約情報をキャンセルしました。'
  rescue Service::UpdateFailure => ex
    flash[:error] = ex.message
  ensure
    redirect_to reservation_management_show_path(_p[:id], @callback)
  end

  private

  # 登録
  def create_params
    params.require(:reservation_management_reservations_entry_form).permit(
      ReservationManagement::Reservations::EntryForm.attribute_keys
    )
  end

  # 更新
  def update_params
    params.require(:reservation_management_reservations_entry_form).permit(
      ReservationManagement::Reservations::EntryForm.attribute_keys
    )
  end

  # 更新(一棟貸し予約情報の個別更新) 更新可能な項目を制限
  def update_params_for_whole
    params.require(:reservation_management_reservations_entry_form).permit(
      :reservation_id, :site_code, :reserve_date, :nationality_id, :visitor_name, :mail_address, :tel, :note
    )
  end

  # 請求情報内訳の更新
  def update_reservation_date_params
    params.permit(reservation_dates: %i(reservation_date_id room_charge cleaning_fee meal_fee))
  end

  def forward_status_params
    params.require(:reservation_management_reservations_show_form).permit(%i(id status))
  end

end

app/helpers/reservation_management/daily_list_helper.rb
module ReservationManagement::DailyListHelper
  def detail_button_tag(row)
    if row.reservation
      link_btn_tag(
        '詳細',
        reservation_management_show_path(row.reservation.id, @callback),
        button_class: 'btn-block btn-success btn-sm')
    else
      return "" unless role_member?
      link_btn_tag(
        '新規',
        reservation_management_entry_date_path(row.search_check_in_day.to_s, row.room.id, @callback),
        button_class: 'btn-block btn-default btn-sm')
    end
  end

  def etc_column_tag(row)
    tag = ''
    if row.reservation&.whole_reservation_id
      tag << content_tag(:div, content_tag(:span, '一棟貸', class: 'badge bg-purple') )
    end
    if row.note.present?
      tag << content_tag(:div, content_tag(:span, '備考あり', class: 'badge bg-red', 'data-toggle': 'tooltip', title: row.note) )
    end
  end
end

app/helpers/reservation_management/entry_helper.rb
module ReservationManagement::EntryHelper
  # 請求内訳編集ボタン
  def edit_reservation_date_link_tag(reservation_id, reservation_date_size)
    link_to(reservation_management_edit_reservation_date_path(reservation_id), 'data-remote': true) do
      options = {class: 'btn btn-success input-sm', type: "button"}
      options[:disabled] = true if reservation_date_size == 1
      content_tag(:button, '請求内訳の編集', options)
    end
  end

  # ステータス変更ボタン
  def forward_status_btn(id:, status:)
    target_status = get_target_status(current_status: status)
    return if target_status.blank?

    label = '「' + reservation_status_name(status: target_status) + '」にする'
    button_tag(type: 'button', class: 'btn btn-warning input-sm', onclick: "forwardStatus('#{@callback}');") do
      label
    end
  end

  # 一棟貸一括ステータス変更ボタン
  def bulk_forward_status_btn(id:, status:)
    target_status = get_target_status(current_status: status)
    return if target_status.blank?

    label = '一棟全部屋を「' + reservation_status_name(status: target_status) + '」にする'
    button_tag(type: 'button', class: 'btn btn-danger input-sm', onclick: "bulkForwardStatus('#{@callback}');") do
      label
    end
  end

  private

  def get_target_status(current_status:)
    target_status = nil
    setting = Settings.RESERVATION.STATUS
    case current_status
    when setting.PREPARING, setting.POSSIBLE, setting.STAYING
      target_status = (current_status.to_i + 1).to_s
    end
    target_status
  end
end

app/helpers/reservation_management/whole_building_entry_helper.rb
module ReservationManagement::WholeBuildingEntryHelper
  
end

app/views/reservation_management/suitebook/_button_entry.html.slim
.col-sm-9.button-area-left
  = link_btn_tag '一覧に戻る',
                  reservation_management_suitebook_transition_search_path,
                  icon_class: 'glyphicon-list-alt',
                  button_class: 'btn-default input-sm'

  = link_btn_tag '詳細に戻る',
                    reservation_management_suitebook_show_path(suitebook_id),
                    button_class: 'btn-default input-sm'

/ .col-sm-3.text-right.button-area-right

app/views/reservation_management/suitebook/_form.html.slim
- submit_label = '登録'

= form_with model: form, scope: :suitebook_reservation_entry, url: reservation_management_suitebook_create_path, local: true, class: 'form-horizontal' do |f|

  = f.hidden_field :suitebook_reservation_id, value: @suitebook.id

  .form-group
    .col-sm-12.text-right
      = f.submit(submit_label , class: "btn btn-primary input-sm", tabindex: 999)

  .form-group
    label.col-sm-2.control-label
      |予約日
      span.require ＊
    .col-sm-3
      .input-group.date
        = f.text_field :reserve_date, class: "form-control calendar", maxlength: 10, tabindex: 1
        span.input-group-addon
          i.fa.fa-calendar

    label.col-sm-2.control-label
      |施設
      span.require ＊
    .col-sm-4
      = f.select :room_id, options_for_select( {'該当する施設がありませんでした' => ''}.merge(room_select_options), form.room_id ), {}, {class: "form-control select2", tabindex: 2}

  .form-group
    label.col-sm-2.control-label
      |宿泊日
      span.require ＊
    .col-sm-3
      .input-group.date
        = f.text_field :check_in_date, class: "form-control calendar", maxlength: 10, tabindex: 3
        span.input-group-addon
          i.fa.fa-calendar

    label.col-sm-2.control-label
      |泊数
      span.require ＊
    .col-sm-1
      = f.number_field :number_of_nights, class: "form-control maxlength", min: 1, max: 31, maxlength: 2, tabindex: 4
    .col-sm-2
        button.btn.btn-block.btn-warning.btn-sm type="button" id="previous_reservation" tabindex=5 予約可否チェック

  .form-group
    label.col-sm-2.control-label
      |予定CI時刻
    .col-sm-3
      .input-group.bootstrap-timepicker.timepicker
        = f.text_field :display_check_in_time, class: "form-control", tabindex: 6
        span.input-group-addon
          i.fa.fa-clock-o
      button.btn.btn-block.btn-default.btn-xs.time_clear type="button" id="time_clear" 予定CI時刻をクリア

  .form-group
    label.col-sm-2.control-label
      |ゲスト名
      span.require ＊
    .col-sm-3
      = f.text_field :visitor_name, class: "form-control maxlength", maxlength: 50, tabindex: 8

  .form-group
    label.col-sm-2.control-label
      |国籍
      span.require ＊
    .col-sm-3
      = f.select :nationality_id, options_for_select( nationality_select_options, form.nationality_id ), {}, {class: "form-control select2", tabindex: 9}

    label.col-sm-2.control-label TEL
    .col-sm-3
      = f.telephone_field :tel, class: "form-control maxlength", maxlength: 20, tabindex: 10, placeholder: "※半角数字、記号（ + - ）のみ"

  .form-group
    label.col-sm-2.control-label メールアドレス
    .col-sm-3
      = f.text_field :mail_address, class: "form-control maxlength", maxlength: 120, tabindex: 11

  .form-group style="margin-bottom: 5px;"
    label.col-sm-2.control-label
      |人数
      span.require style="margin-right:10px;" ＊
      |大人
    .col-sm-1 style="text-align:left;"
      = f.number_field :adult_count, class: "form-control maxlength", min: 1, maxlength: 2, tabindex: 12

  .form-group
    label.col-sm-2.control-label 子供
    .col-sm-1 style="text-align:left;"
      = f.number_field :child_count, class: "form-control maxlength", min: 0, maxlength: 2, tabindex: 13

    label.col-sm-1.control-label 合計
    .col-sm-1
      = f.number_field :total_count, class: "form-control", disabled: true

  .form-group
    label.col-sm-2.control-label
      |宿泊料
      span.require ＊
    .col-sm-3
      = f.text_field :room_charge, class: "form-control maxlength", maxlength: 12, tabindex: 14

  .form-group
    label.col-sm-2.control-label
      |清掃費
      span.require ＊
    .col-sm-3
      = f.text_field :cleaning_fee, class: "form-control maxlength", maxlength: 12, tabindex: 15

  .form-group
    label.col-sm-2.control-label
      |食事代
      span.require ＊
    .col-sm-3
      = f.text_field :meal_fee, class: "form-control maxlength", maxlength: 12, tabindex: 15

    label.col-sm-2.control-label
      |予約サイト
      span.require ＊
    .col-sm-3
      = f.select :site_code, options_for_select( site_select_options, form.site_code ), {}, {class: "form-control select2", tabindex: 16}

  .form-group
    label.col-sm-2.control-label 合計
    .col-sm-3
      = f.text_field :total, class: "form-control", disabled: true, placeholder: "自動計算"

  .form-group
    label.col-sm-2.control-label 備考
    .col-sm-8
      = f.text_area :note, row: 4, class: "form-control maxlength", maxlength: 500, placeholder: "５００文字まで入力可能です。", tabindex: 17

  .form-group
    .col-sm-12.text-right
      = f.submit(submit_label , class: "btn btn-primary input-sm", tabindex: 999)

/ 予約可否チェックモーダル
.previous_reservation_modal

javascript:

  // 予約可否チェックボタン押下時Ajax送信後モーダル起動
  $('#previous_reservation').click(function() {
    var check_in_date = $('#suitebook_reservation_entry_check_in_date').val();
    if(check_in_date === "") {
      alert("宿泊日を入力してください！");
      $('#suitebook_reservation_entry_check_in_date').focus();
      return false;
    }
    var number_of_nights = $('#suitebook_reservation_entry_number_of_nights').val();
    if(number_of_nights === "" || number_of_nights === "0") {
      alert("泊数を１以上で入力してください！");
      $('#suitebook_reservation_entry_number_of_nights').focus();
      return false;
    }
    $('#reservation_entry_form').spin();
    var room_id = $('#suitebook_reservation_entry_room_id').val();
    var reservation_id = $('#suitebook_reservation_entry_reservation_id').val();
    var path = '#{raw modal_search_reservation_previous_reservation_path}';
    var data = 'check_in_day=' + check_in_date;
    data    += '&number_of_nights=' + number_of_nights;
    data    += '&room_id=' + room_id;
    //data    += '&reservation_id=' + reservation_id;
    $.post( path, data );
  })

app/views/reservation_management/suitebook/_search.html.slim
= form_with model: form, url: reservation_management_suitebook_search_path, scope: :search_suitebook, class: "form-horizontal" do |f|
  .box.box-danger
    .box-header.with-border
      .box-title 検索条件
      .box-tools.pull-right
        button.btn.btn-box-tool type="button" data-widget="collapse" data-toggle="tooltip" title="" data-original-title="Collapse"
          |検索条件ウィンドウを開閉する&nbsp;
          i.fa.fa-minus
          / i.fa.fa-plus

    .box-body

      .form-group
        label.col-sm-2.control-label データ取込日
        .col-sm-6
          .input-group.date.col-sm-4 style="float: left;"
            = f.text_field :search_import_date_from, class: "form-control", maxlength: 10
            span.input-group-addon
              i.fa.fa-calendar

          .form-control-static.col-sm-1.text-center 〜

          .input-group.date.col-sm-4 style="float: left;"
            = f.text_field :search_import_date_to, class: "form-control", maxlength: 10
            span.input-group-addon
              i.fa.fa-calendar

      .form-group
        label.col-sm-2.control-label 宿泊日
        .col-sm-6
          .input-group.date.col-sm-4 style="float: left;"
            = f.text_field :search_check_in_date, class: "form-control", maxlength: 10, placeholder: 'CI日'
            span.input-group-addon
              i.fa.fa-calendar

          .form-control-static.col-sm-1.text-center 〜

          .input-group.date.col-sm-4 style="float: left;"
            = f.text_field :search_check_out_date, class: "form-control", maxlength: 10, placeholder: 'CO日'
            span.input-group-addon
              i.fa.fa-calendar

      .form-group
        label.col-sm-2.control-label ステータス
        .col-sm-2
          = f.select :search_status, options_for_select( suitebook_status_select_options, form.search_status ), {}, {class: "form-control select2"}

      .form-group
        label.col-sm-2.control-label ゲスト名
        .col-sm-5
          = f.text_field :search_visitor_name, class: "form-control maxlength", maxlength: 50

        .col-sm-5.text-right
          = link_to reservation_management_suitebook_path do
            button.btn.btn-default.clear-btn type="button" クリア
          button.btn.btn-default.search-btn type="submit"
            i.fa.fa-search 検索

app/views/reservation_management/suitebook/entry_whole.html.slim
- breadcrumb :suitebook_entry_whole, @suitebook.id
- provide(:title, t('title.suitebook.entry_whole'))

.row
  .col-xs-12
    .box.box-primary
      .box-tools.pull-right
        button.btn.btn-box-tool type="button" data-widget="remove"
          i.fa.fa-remove
      .box-body
        p suitebook連携データを元に一棟貸予約情報を登録します。
        ul
          li
            |「予約可否チェック」ボタンは、
            b.attention 施設・宿泊日・泊数
            |で予約可能かを確認します。別の画面や他のユーザーが先に予約情報を登録した場合、この予約情報は登録できません。
          li 国籍についてはsuitebookから情報が取得できないため、「その他」が自動的に選択された状態となります。適宜変更してください。

.row
  .col-xs-12
    = render 'shared/error_messages', obj: @form

.row
  = render 'button_entry', suitebook_id: @suitebook.id

.row
  .col-xs-12
    .box.box-warning
      .box-body.suitebook_reservation_entry
        = render '/reservation_management/whole_reservation/form', form: @form, action: 'create', suitebook_reservation_id: @suitebook.id, url: reservation_management_suitebook_create_whole_path

.row
  = render 'button_entry', suitebook_id: @suitebook.id

app/views/reservation_management/suitebook/search.js.erb
$('#suitebook_list').html('<%= j(render "list", form: @form) %>');
// Ajaxでのパーシャル更新時は明示的ローディングを停止させる
// $('#daily_search_form').spin(false);
stopSpin($('.form-horizontal'));